### ISSUE TITLE
Split into multiple loaders

### ISSUE THREAD

**Issue by cletusw** [webpack-contrib/polymer-webpack-loader#22]
According to https://webpack.js.org/development/how-to-write-a-loader/#guidelines,

> * Loaders should do only a single task
> * Loaders can be chained. Create loaders for every step, instead of a loader that does everything at once.

For example, I'm very interested in the HTML Imports -> ES6 import transform for a specific project, but not the other pieces. Ideally, that piece would be isolated as `html-imports-webpack-loader` ([`html-imports-loader`](https://github.com/vagusX/html-imports-loader) is taken and seems to be a different thing entirely).

**Comment by ChadKillingsworth** [comment]
This loader is very much inline with other similar loaders. Specifically look at the [Vue Loader](https://github.com/vuejs/vue-loader). The purpose of this loader is to allow existing polymer projects to use webpack with as little friction as possible.

This project is designed to be chainable. We already chain it to a babel loader. It's a todo to provide better options for the HTML and CSS content.

There's probably some very good uses for something like a `html-imports-webpack-loader`, but that's not this projects goal. You are welcome to create one though.
