### ISSUE TITLE
HTML Loader Intregration

### ISSUE THREAD

**Issue by michael-ciniawsky** [webpack-contrib/polymer-webpack-loader#29]
👋 I'm currently applying `webpack-defaults` to `html-loader` and since this will be a major release anyways, it's possible to change certain behaviours if required 😛 . The current `html-loader` always exports a `module` and therefore can't be chained as a 'previous' loader, which makes it unusable with `polymer-webpack-loader` atm. `html-loader` takes care of template literals and assets resolving (`<img src="${require('./image.png')}">`). So the question is if this is needed here :). If I can update the loader to export a `{String}` instead in case it isn't the last loader in the loaders chain 

**src/index.js**
```js
if (this.loaderIndex !== 0) {
  return `${html}` // {String}
}

return `export default ${html}` // {Module}
```

### Usage 

**webpack.confg.js**
```js
...
{
   test: /\.html$/,
   use: [
      'polymer-webpack-loader',
      'html-loader'
   ]
}
...
```

**Comment by ChadKillingsworth** [comment]
We definitely want to support this behavior somehow.

A string is a possibility - or potentially a sub-loader. The [vue loader](https://vue-loader.vuejs.org/en/configurations/advanced.html#webpack-2x) supports embed loaders for specific sections.

This is going to come up with CSS as well.

**Comment by ChadKillingsworth** [comment]
@michael-ciniawsky After thinking about this for several days, returning a string (or providing the option to return a string) would be extremely helpful.

**Comment by ChadKillingsworth** [comment]
@michael-ciniawsky I ran test cases. I think we're going to need to use the concept of pre-processors like the [vue-loader](https://vue-loader.vuejs.org/en/configurations/pre-processors.html). Every other scenario I've tried fails in one way or another.

We were going to tackle this anyway for CSS.

**Comment by michael-ciniawsky** [comment]
```js
{
   test: /\.html$/
   use: {
      loader: 'polymer-webpack-loader',
     options: {
        // option to register a callback/hook
        // per `<dom-element>` (component)
        // for preprocessors (options.transform || options.preprocess)
        transform: {
          styles: (style) => {
            // for e.g
            return postcss(plugins)
              .process(style, options)
              .then({ css } => css)
           },
           template: (html) => {
             // for e.g
             return posthtml(plugins)
               .process(html, options)
               .then({ html } => html)
            },
            scripts: (code) => {
              // for e.g
              return babel.transform(code)
            }
          },
          ...options
        }
      }
   }
}
```
