### ISSUE TITLE
Loading from node_modules

### ISSUE THREAD

**Issue by slanted** [webpack-contrib/polymer-webpack-loader#30]
Nice work! I'm wondering if I could load web-components that I've published to NPM from the node_modules directory.

I've modified your my-element.html in the demo directory so it starts like this:

```
<link rel="import" href="../bower_components/polymer/polymer-element.html"> 
<link rel="import" href="../node_modules/my-npmelement/my-npmelement.html"> 
...
<my-npmelement></my-npmelement>
...
```

And according to your documentation I should be able to modify my webpack.config.js to this:
...
```
module: {
    rules: [
      {
        // If you see a file that ends in .html, send it to these loaders.
        test: /\.html$/,
        // cant i just do this?????
        include: ['bower_components','node_modules'],
        // This is an example of chained loaders in Webpack.
        // Chained loaders run last to first. So it will run
        // polymer-webpack-loader, and hand the output to
        // babel-loader. This let's us transpile JS in our `<script>` elements.
        use: [
          { loader: 'babel-loader' },
          { loader: 'polymer-webpack-loader' }
        ]
      },
      {
        // If you see a file that ends in .js, just send it to the babel-loader.
        test: /\.js$/,
        use: 'babel-loader',
        // This line tells Webpack not to transpile .js files coming out of
        // node_modules.
        exclude: /node_modules/
      }
    ]
  },
```
...

Seem ok? Or am I missing something here? When I load the page with this modification I get a syntax error: invalid-token. I've also tried it like this:

```
use: [
          { loader: 'babel-loader' },
          { 
            loader: 'polymer-webpack-loader',
            include: ['bower_components','node_modules']
          }
        ]
```

And then I get an invalid schema error.

**Comment by ChadKillingsworth** [comment]
You can definitely load web components out of the node_modules folder. I'd have to create a valid reproduction case to test your config.

**Comment by slanted** [comment]
@ChadKillingsworth thanks Chad, according to the docs I thought that 

`include: ['bower_components','node_modules'] `

should work. But no luck yet.

**Comment by bryandcoulter** [comment]
@slanted Hi, there are a few different things that would come into play when trying to modify the demo app to use other components. With out being able to see your build run it would be hard to target. I have set up a demo repo using npm elements. https://github.com/bryandcoulter/npm-elements-example. Give this a shot and if you have an question or issues let me know.

**Comment by ChadKillingsworth** [comment]
I'm closing this until we have a firm problem to work on. Importing from node_modules definitely works as long as the import path is relative or absolute: `<link rel="import" href="/node_modules/...">` or `<link rel="import" href="../node_modules/...">`.
