### ISSUE TITLE
Fix the demo to correctly transpile the template registration helper script

### ISSUE THREAD

**Issue by constantijn** [webpack-contrib/polymer-webpack-loader#33]
If i checkout the latest project and try to run `webpack --optimize-minimize` on the demo it crashes with `ERROR in bundle.js from UglifyJs Unexpected token: name (RegisterHtmlTemplate) [bundle.js:72,6]`

I did some digging and it looks like the the `polymer-webpack-loader` does a strait up `const RegisterHtmlTemplate = require('polymer-webpack-loader/register-html-template');` and then drops it in the bundle.js bypassing all babel processing.

Therefore we get a `class RegisterHtmlTemplate {` defenition in the bundle.js even if we're trying to output ES5 code that goes to uglify. Since classes aren't ES5 we get a crash.

Maybe rewrite register-html-template as ES5? or make sure it gets passed trough babel?

**Comment by ChadKillingsworth** [comment]
We might need to address this in the readme, but it is a dev responsibility to make sure this component gets transpiled if needed. Polymer 2.0 wishes to support shipping ES6 style code to browsers that support it as do we.

**Comment by constantijn** [comment]
Fair enough, but the way it's setup now this bit of code gets ignored by babel.
All the sample code goes trough babel, and then this bit of ES6 gets tacked on in the end as is. 
I could fix this by chaining the loaders so that it goes `babel-loader -> polymer-webpack-loader -> babel-loader (again) -> minify` but that seems clunky.

Is there a more elegant way to set things up so that the contents of register-html-template.js also gets passed trough babel?

it would be nice if webpack standard features like `webpack -p` work out of the box.

**Comment by ChadKillingsworth** [comment]
I'm guessing you just need to add this file to your normal babel loader include. For instance mine looks like:

```js
{
	test: /\.js$/,
	loader: 'babel-loader',
	include: [
		path.resolve(__dirname, '../src'),
		path.resolve(__dirname, '../node_modules/@banno/polymer'),
		path.resolve(__dirname, '../node_modules/polymer-webpack-loader'),
	],
	options: {
		presets:  [ 'es2015' ],
		plugins: [ 'transform-runtime' ]
	}
}
```

**Comment by constantijn** [comment]
If i do that it ends up in my bundle.js twice. Once neatly passed trough babel, and once again as is.
The problem seems to be that `polymer-webpack-loader` seems to forcibly add a copy of `polymer-webpack-loader/register-html-template.js` to the bundle.js, as is, without passing it trough the other loaders.

**Comment by constantijn** [comment]
Is there a way the contents of `olymer-webpack-loader/register-html-template.js` can be passed trough babel also? Because the javascript in the <script> tags of my .html webcomponents does get processed by babel correctly.

**Comment by ChadKillingsworth** [comment]
> If i do that it ends up in my bundle.js twice. Once neatly passed trough babel, and once again as is.

Something is definitely wrong then. If you can post your config, I might be able to help. It's not duplicated in my bundles.

**Comment by constantijn** [comment]
I tried following the example in the /demo directory of this repo and building from there.

webpack.config.babel.js
```
const HtmlWebpackPlugin = require('html-webpack-plugin');
const CopyWebpackPlugin = require('copy-webpack-plugin');
const path = require('path');

const config = {
  entry: path.resolve(__dirname, 'src/index.js'),
  output: {
    filename: 'bundle.js',
    path: path.resolve(__dirname, 'dist'),
  },
  resolve: {
    modules: [
      path.resolve(__dirname, 'node_modules'),
      path.resolve(__dirname, 'bower_components'),
    ],
  },
  module: {
    rules: [
      {
        test: /\.html$/,
        use: [
          {loader: 'babel-loader'},
          {loader: 'polymer-webpack-loader'},
        ],
      },
      {
        test: /\.js$/,
        use: 'babel-loader',
        exclude: /node_modules/,
      },
    ],
  },
  devServer: {
    contentBase: path.join(__dirname, 'dist'),
    compress: true,
    port: 9010,
    historyApiFallback: {
      index: 'index.html',
    },
    proxy: {
      '/api': {
        target: 'http://localhost:9000',
        pathRewrite: {'^/api': ''},
      },
    },
  },
  devtool: 'source-map',
  plugins: [
    // This plugin will generate an index.html file for us that can be used
    // by the Webpack dev server. We can give it a template file (written in EJS)
    // and it will handle injecting our bundle for us.
    new HtmlWebpackPlugin({
      template: path.resolve(__dirname, 'src/index.ejs'),
      inject: false,
    }),
    // This plugin will copy files over for us without transforming them.
    // That's important because the custom-elements-es5-adapter.js MUST
    // remain in ES2015.
    new CopyWebpackPlugin([{
      from: path.resolve(__dirname, 'bower_components/webcomponentsjs/*.js'),
      to: 'bower_components/webcomponentsjs/[name].[ext]',
    }]),
  ],
};

module.exports = config;
```
.babelrc 
```
{
  "presets": [
    [
      "env",
      {
        "targets": {
          "browsers": [
            "last 2 versions"
          ]
        },
        "loose": true
      }
    ],
    "stage-2"
  ]
}
```

**Comment by constantijn** [comment]
Stept to reproduce:
- Checkout this project from master
- do to the demo directory
- Add my .babelrc
- yarn add -D babel-preset-stage-2
- run webpack

After that build/bundle.js has all classes compiled down to ES5, except the `class RegisterHtmlTemplate` near the top of bundle.js

**Comment by constantijn** [comment]
IF you want to see the duplication change the entry in the webpack config to 

`entry: [path.resolve(__dirname, 'src/index.js'), path.resolve(__dirname, 'node_modules/polymer-webpack-loader/register-html-template.js')],`

**Comment by ChadKillingsworth** [comment]
> `exclude: /node_modules/,`

Ahh that's wrong. The demo shouldn't have that. I'll see about a fix and ping @robdodson for review.

**Comment by constantijn** [comment]
Ahh, makes sense, removing that line fixes it.
Thanks for looking into it!

**Comment by robdodson** [comment]
sent in a PR to update the webpack config and updated the blog posts
