### ISSUE TITLE
HTTP URL's incorrectly handled as local resources

### ISSUE THREAD

**Issue by AlexHenkel** [webpack-contrib/polymer-webpack-loader#35]
*From @dulimarta [issue](https://github.com/Banno/polymer-2-starter-kit-webpack/issues/4)*

When trying to include an absolute HTTP link, such as a Google Font, this gets compiled as a local resource. An example is when using any *paper-element* that depends on `font-roboto` package.
```
Module not found: Error: 
Can't resolve '${PROJECT_PATH}/bower_components/font-roboto/https:/fonts.googleapis.com/css?family=Roboto....
```

Steps to reproduce error

1. Use webpack adapted Starter Kit: `git clone https://github.com/Banno/polymer-2-starter-kit-webpack.git`
2. Import some paper element `bower install --save paper-item`
3. Include dependency `<link rel="import" href="../bower_components/paper-item/paper-item.html">`
4. Run `webpack`

**Comment by ChadKillingsworth** [comment]
I'm guessing this is related to #34
