### ISSUE TITLE
Consider supporting vanilla web component

### ISSUE THREAD

**Issue by kyuwoo-choi** [webpack-contrib/polymer-webpack-loader#39]
First, thank you for starting this project.
I was thinking about how to build a web component web pack loader for a while.

Sure, I like Polymer and I already have done one project with it, but now I want to start a project with Vanilla Web Components.
I have tested the code below with the polymer-webpack-loader, and I think it's enough for Vanilla Web Components.

Here's a short code I started.
```html
<link rel="import" href="./your-element.html">

<template id='my-element'>
  <h1>Hello, World! It's today.</h1>
  <your-element></your-element>
</template>
<script>
  class MyElement extends HTMLElement {
    constructor() {
      super();

      const shadowRoot = this.attachShadow({mode: 'open'});
      const template = document.querySelector('#my-element');
      shadowRoot.appendChild(template.content.cloneNode(true));
    }
  }

  window.customElements.define('my-element', MyElement);
</script>
```

The problem is that the above code can not get the `template` used in` MyElement`'s `constructor`.
Transforming the above code will cause the `template` to be executed on the` DOMContentLoaded` event by `RegisterHtmlTemplate.toBody`, but the JavaScript inside the` script` will be executed immediately.
Of course, if you defer attribute on a transfiled script file, you can use it without problems, but if possible, I think polymer-webpack-loader should solve it.

I wonder if you guys are going to support the vanilla web component. If I so, I would be happy to send PR.

**Comment by ChadKillingsworth** [comment]
This is already supported. You just need to ensure that your bundle script include in your index.html file is included  in such a way that `document.body` exists when it executes. You can use the `defer` attribute as you mentioned, or place the script in the body.

How you do this is highly dependent on what techniques you use for your index.html file. You can see an [example in the demo](https://github.com/webpack-contrib/polymer-webpack-loader/blob/master/demo/src/index.ejs#L38).

**Comment by kyuwoo-choi** [comment]
Thanks for the quick answer @ChadKillingsworth 

Yes, I can use it like the example code you gave, put bundle script when the `body` exists, or add the `defer` attribute. But if the script is in the head, that's a problem.

If you look at the [code](https://github.com/webpack-contrib/polymer-webpack-loader/blob/master/register-html-template.js#L41-L47), you are already processing the `html element` depending on whether the `body` exists or not. I think that the condition should be applied to the script as well. Then the bundled script will be fine wherever it is.

And the example code you gave is loading the script on the `Web Components Ready` event `webcomponents-loader` fires. It may be necessary today, but I think you need to consider the condition that no `webcomponents-loader`. It is just polyfill right? The `polymer-webpack-loader` should work regardless of the presence of the `webcomponents-loader`.

good day :)

**Comment by ChadKillingsworth** [comment]
The loader isn't designed to process the main html document (there are other loaders and plugins for that). Neither does the loader have any knowledge of how the bundle is included in the index.html page.

What you are asking for is reasonable, but it is beyond the scope of this project.

**Comment by kyuwoo-choi** [comment]
Hello @ChadKillingsworth 

Maybe you misunderstood what I said.
`polymer-webpack-loader` do not need to understand index.html at all.

What I'm talking about is that the module scripts should be run after the corresponding template is registered via the register-html-template.
[register-html-template L41-L47](https://github.com/webpack-contrib/polymer-webpack-loader/blob/master/register-html-template.js#L41-L47)

I wrote a little bit of dirty code to check the ideas
[index.js L195](https://github.com/webpack-contrib/polymer-webpack-loader/blob/master/src/index.js#L195)
```js
source += `const exec = () => {
  ${scriptContents}
};
if (!document.body) {
  document.addEventListener('DOMContentLoaded', exec);
} else {
  exec();
}`;
```

I think the `exec` function should be out like register-html-template.js
Of course, I haven't care about TC, sourcemap, and so on ...

I would like to send a PR but I am hesitant because there seems to be a few things to be decided prior to implementation.

Tell me your thoughts.

**Comment by ChadKillingsworth** [comment]
I didn't suggest that option because it changes script semantics in breaking ways outside of developer control. For instance, the webpack shimming mechanisms wouldn't properly work, scoping and the `this` keyword are impacted and the script no longer synchronously executes.

While I realize you want this to be an automatic process for your use case, it's beyond the scope of this loader.

**Comment by kyuwoo-choi** [comment]
yea agree.

BTW. I'm still trying to apply a polymer-webpack-loader to a vanilla web component.
When I insert a script as a reference, I have another problem.
This is because the code that uses templates in javascript will always run before adding templates to the DOM, as transfiled as in the code below.

As you said If this loader also supports the web component, I think the execution order of the script and template should be managed.

```js
// TRANSLATED
// CONCATENATED MODULE: ./src/my-element.html
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_0__my_element_js__ = __webpack_require__(2);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_0__my_element_js___default = __webpack_require__.n(__WEBPACK_IMPORTED_MODULE_0__my_element_js__);

const RegisterHtmlTemplate = __webpack_require__(1);
RegisterHtmlTemplate.toBody('<template id="my-element"> <div>template</div> </template> ');
```

```html
<!-- my-element.html -->
<link rel="import" href="./your-element.html">

<template id='my-element'>
  <div>template</div>
</template>
<script src="./my-element.js"></script>
```

```js
// my-element.js
  class MyElement extends HTMLElement {
    constructor() {
      super();

      const shadowRoot = this.attachShadow({mode: 'open'});
      const template = document.querySelector('#my-element');
      shadowRoot.appendChild(template.content.cloneNode(true));
    }
  }

  window.customElements.define('my-element', MyElement);
```
