### ISSUE TITLE
Module not found: Error: Can't resolve polymer-element.html

### ISSUE THREAD

**Issue by shobson** [webpack-contrib/polymer-webpack-loader#42]
I'm just trying to get your demo project up and running. I followed the steps, npm i, bower i, and npm start. It seems to fail saying "Module not found: Error: Can't resolve pathtopolymer-element.html" removes the '/''s in the path. I havent changed anything, just pulled down the demo and tried to run it and I am getting this error. Any help would be greatly appreciated! Thanks!

**Comment by bryandcoulter** [comment]
@shobson Hi, we are having trouble reproducing the issue. If at all possible could you send us a console screen capture of the error message and operating system specs?  That will helps us greatly in narrowing down the issue.

**Comment by shobson** [comment]
Sure. I am on windows 7, here is the error im getting in console when running npm start.

`ERROR in ./src/my-element.html
Module not found: Error: Can't resolve 'C:UsersshobsonDesktoppolymer-webpack-loader-masterdemower_componentspolymerpolym
er-element.html' in 'C:\Users\shobson\Desktop\polymer-webpack-loader-master\demo\src'
 @ ./src/my-element.html 5:0-109
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:9000 ./src/index.js
Child html-webpack-plugin for "index.html":
       [0] (webpack)/buildin/amd-options.js 82 bytes {0} [built]
       [1] ./node_modules/html-webpack-plugin/lib/loader.js!./src/index.ejs 2.49 kB {0} [built]
       [2] ./node_modules/lodash/lodash.js 478 kB {0} [built]
       [3] (webpack)/buildin/global.js 823 bytes {0} [built]
       [4] (webpack)/buildin/module.js 521 bytes {0} [built]
webpack: Failed to compile.`

**Comment by ChadKillingsworth** [comment]
That looks awfully close to the same thing as #28. Are you sure you are using the latest version? We published 1.2.4 last night.

**Comment by shobson** [comment]
Hmm just checked my package.json and it seems it was set to 1.2.1. I changed it to 1.2.4 and re-ran the npm install, bower install and npm start. Seems to be working now! Thanks!
