### ISSUE TITLE
prpl-server-node build support by default

### ISSUE THREAD

**Issue by Brian-McBride** [webpack-contrib/polymer-webpack-loader#62]
I'm wondering if the build process or docs around this loader might also supply directions on building for prpl-server-node
https://github.com/Polymer/prpl-server-node

I realize that configuring webpack is a little out of scope from a polymer loader module, however in interest in supporting developers new to Polymer and PRPL to achieve faster best-practices and super high [lighthouse](https://developers.google.com/web/tools/lighthouse/) scores. 

I'm making the ask here based on this team's polymer + webpack expertise.

**Comment by ChadKillingsworth** [comment]
We'd like to expand the demo folder with multiple demo options. We can just move the existing demo to a "basic" subfolder.

So if you'd like to work up a demo using prpl-server-node, by all means submit it here as a reference.

**Comment by Brian-McBride** [comment]
Thank's Chad. 
I'll do just that. I'm a bit new to webpack, but I'll see if I can get a nice reference build that matches what the PRPL node server is looking for. I'll add a link here when I have a bit more in place.
