### ISSUE TITLE
Unable to build using polymer-webpack-loader

### ISSUE THREAD

**Issue by mvinayakam** [webpack-contrib/polymer-webpack-loader#66]
Hello

I am unable to build a clean dist using polymer-webpack-loader.  Please see github link for sample project - https://github.com/simpleharshit/demo-pwa

Launching the app after passing it through polymer-webpack-loader shows this on the page -

 const RegisterHtmlTemplate = require('polymer-webpack-loader/register-html-template'); RegisterHtmlTemplate.toBody(" ");

Can you please help locate the problem?

https://stackoverflow.com/questions/46283273/building-with-webpack3-6-0-polymer-webcomponents-and-angular-4-fails

**Comment by ChadKillingsworth** [comment]
You can't chain the raw loader like that.

**Comment by mvinayakam** [comment]
Thank you for the update. Can you please guide me to some documentation or link which help us move forward?
