### ISSUE TITLE
"polymer-webpack-loader" -> "polymer-loader" ?

### ISSUE THREAD

**Issue by JonDum** [webpack-contrib/polymer-webpack-loader#67]
Owner of `polymer-loader` here. I wrote `polymer-loader` over 2 years ago when this project didn't exist. As of now, I don't use polymer nor maintain that repo.

If you guys want to rename this project `webpack-contrib/polymer-loader` to maintain consistency with all the other webpack contrib libraries I'll gladly relinquish the npm `polymer-loader` space.

**Comment by michael-ciniawsky** [comment]
That would be highly appreciated I guess, personally thanks in advance 👍 

cc @d3viant0ne @ChadKillingsworth @bryandcoulter @robdodson

**Comment by d3viant0ne** [comment]
Completely up to @ChadKillingsworth & team, changing things on our end is simple enough should they decide to go that route.

**Comment by ChadKillingsworth** [comment]
I definitely appreciate the offer. Renaming github repos is easy - renaming npm packages not so much. Maybe @JonDum you can just use `npm deprecate` and update the readme to point to this package?

Otherwise we'll be stuck double publishing for a while.

**Comment by JonDum** [comment]
Done and done. 

Big ol' warning on [README](https://github.com/JonDum/polymer-loader#warning-no-longer-maintained)

And I `npm deprecate`'d the package on npm. 

If y'all want to go ahead with the rename/double publish for consistency, let me know and I'll either unpublish or `npm owner add` whoever you'd like (or your team account? not sure how npm teams work).
