### ISSUE TITLE
Load bundle earlier while waiting for WebComponentsReady event

### ISSUE THREAD

**Issue by ernsheong** [webpack-contrib/polymer-webpack-loader#69]
First of all, thanks for this! Could not be more timely as the official solution leaves a lot of gaps.

Right now, the demo of polymer-webpack-loader seems to wait for "WebComponentsReady" event before attemping to load the bundle:
https://github.com/webpack-contrib/polymer-webpack-loader/blob/master/demo/src/index.ejs#L37

Can we do better? This affects time to first paint/render (performance). There is a slight pause before the bundle even starts to load:
![image](https://user-images.githubusercontent.com/1343284/31449739-4e658a04-aeda-11e7-8ba5-d9bbd494b89c.png)

**Comment by ChadKillingsworth** [comment]
To do better you either need to:

 * Use `document.write` to add the polyfills synchronously
 * Always include `webcomponents-lite.js` regardless of browser capabilities
 * Use server-side rendering based on user agent to determine which set of polyfills to return.

You are free to experiment and choose your preferred method, but it is very tricky to get correct for all browsers.

**Comment by ChadKillingsworth** [comment]
I should also mention it's possible to compile and bundle the polyfills in with your main bundle, but that is also non-trivial.

**Comment by ernsheong** [comment]
Here's something quick that bridges that gap. Price to pay is that the bundle is inlined within index.html, which isn't too huge of a price. Assumes fetch is available.

Basically proceed to load bundle without waiting for WebComponentsReady event. Once event is ready, immediately inlines bundle.

```
<script>
    (function() {
      const bundlePromise = fetch("<%= htmlWebpackPlugin.files.js[0] %>")
        .then((response) => response.text());

      document.addEventListener("WebComponentsReady", function componentsReady() {
        document.removeEventListener("WebComponentsReady", componentsReady, false);

        bundlePromise
          .then((bundle) => {
            const script = document.createElement("script");
            script.text = bundle;
            var refScript = document.getElementsByTagName("script")[0];
            refScript.parentNode.insertBefore(script, refScript);
          });
      }, false);
    })();
  </script>
```

Gap is bridged:
![image](https://user-images.githubusercontent.com/1343284/31451208-19e9bea4-aede-11e7-8271-24ab6e2f6cd4.png)

**Comment by ernsheong** [comment]
Here's something quick to bridge the gap. Price to pay is the inlining of the JS bundle. Assumes `fetch` availability for convenience.

```js
 <script>
    (function() {
      // Load bundle first without waiting for WebComponentsReady.
      const bundlePromise = fetch("<%= htmlWebpackPlugin.files.js[0] %>")
        .then((response) => response.text());

      document.addEventListener("WebComponentsReady", function componentsReady() {
        document.removeEventListener("WebComponentsReady", componentsReady, false);

        // Polyfill is done, let's go :)
        bundlePromise
          .then((bundle) => {
            const script = document.createElement("script");
            script.text = bundle;
            var refScript = document.getElementsByTagName("script")[0];
            refScript.parentNode.insertBefore(script, refScript);
          });
      }, false);
    })();
</script>
```

Gap is gone:
![image](https://user-images.githubusercontent.com/1343284/31451764-888a9c88-aedf-11e7-8a6f-09d0e538b899.png)

**Comment by ChadKillingsworth** [comment]
If that's all you are trying to solve, you can just add a preload tag:

```html
<link rel="preload" href="main.bundle.js" as="script"/>
```

Your current solution requires any content security policy to allow inline scripts.
