### ISSUE TITLE
Shimming Recipe for Web Component Tester?

### ISSUE THREAD

**Issue by rawberg** [webpack-contrib/polymer-webpack-loader#73]
Trying to test components with WCT. Got the bundle loading in the test suite but none of the custom elements are available. Is there a shimming recipe to get WCT to see the elements defined in the bundle?

**Comment by ChadKillingsworth** [comment]
I don't have great familiarity with what WCT is expecting. How is it looking for elements? How is it referencing them?

**Comment by rawberg** [comment]
I'm not a WCT expert but it's expecting things to be included via html imports. I was able to get it working for now by including the component I'm testing via html imports. I think I will have to go back and remove anything inside my components that are relying on features being provided by Babel. I'll close this for now. If anybody else comes up with a better approach please add to this issue.
