### ISSUE TITLE
Cannot uglify the bundle

### ISSUE THREAD

**Issue by nicolasmoise** [webpack-contrib/polymer-webpack-loader#75]
Putting a `plugins: [new webpack.optimize.UglifyJsPlugin()]` breaks the build with the following message

```
ERROR in main.js from UglifyJs
    Unexpected token: name (dedupeId)
```

Because you cannot uglify ES2015.

**Comment by ChadKillingsworth** [comment]
This is known - you need a transpiler. See the demo:

https://github.com/webpack-contrib/polymer-webpack-loader/blob/master/demo/webpack.config.js#L40-L46
