### ISSUE TITLE
Use Travis for CI

### ISSUE THREAD

**Issue by ChadKillingsworth** [webpack-contrib/polymer-webpack-loader#8]
Once #3 has been implemented, we should use Travis to automatically run tests for all PRs. In addition, Travis can automatically handle npm publishing for us.

**Comment by ChadKillingsworth** [comment]
Webpack-contrib doesn't use travis for deployment. We do need to add travis integration.

**Comment by evilebottnawi** [comment]
@d3viant0ne seems your need here
@ChadKillingsworth we use `webpack-defaults` (https://github.com/webpack-contrib/webpack-defaults) for consistent code across all repos in `webpack-contrib`

**Comment by ChadKillingsworth** [comment]
@evilebottnawi See #19. This issue predates transferring the repo to webpack-contrib.
