### ISSUE TITLE
Global styles ordering incorrect

### ISSUE THREAD

**Issue by LarsDenBakker** [webpack-contrib/polymer-webpack-loader#84]
`registerHtmlTemplate.toBody()` inserts styles before the body's first child. (https://github.com/webpack-contrib/polymer-webpack-loader/blob/master/register-html-template.js#L42) This causes global styles to be inserted in the opposite order than they would be when produced by regular HTML imports and/or the polymer build.

We are moving our app to use webpack, and override some of the global styles of the paper elements. We rely on the style ordering for this.

**Comment by ChadKillingsworth** [comment]
You want to send in a PR to fix this?

**Comment by LarsDenBakker** [comment]
Sure, no problem. One question I had is why you're appending to the body, and not the head? The head is generally the place for these things to go.

**Comment by ChadKillingsworth** [comment]
I _think_ because that more closely mimics what happened with an imported Polymer Element. I'm not 100% sure - we'd have to ask @bryandcoulter.

**Comment by LarsDenBakker** [comment]
If you check https://shop.polymer-project.org/, the styles are rendered in the head. It's separate to this issue, but it feels weird to have these things rendered in the body :)
